use crate::entry::{ConceptCategory, ConceptEntry, DescriptionEntry, DescriptionKind};

pub static TYPES: ConceptEntry = ConceptEntry {
    name: "types",
    summary: "rl's primitive types - int, float, bool, string, char, and byte - each with a mandatory declared type checked at compile time",
    category: ConceptCategory::Syntax,
    prerequisites: &[],
    descriptions: &[
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("static typing"),
            description: "rl is statically typed - every variable has a declared type, checked at compile time",
            examples: &[
                "dec int    x = 42",
                "dec float  y = 3.14",
                "dec bool   b = true",
                "dec string s = \"hello\"",
                "dec char   c = 'a'",
            ],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("int"),
            description: "`int` is a 64-bit signed integer, and the default type of any bare integer literal",
            examples: &["dec int x = 100\ndec int neg = -42\nprintln(neg)  // -42"],
            expected_output: &["-42"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("float"),
            description: "`float` is a 64-bit floating point number",
            examples: &["dec float pi = 3.14\nprintln(pi)  // 3.14"],
            expected_output: &["3.14"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("bool"),
            description: "`bool` is either `true` or `false`",
            examples: &["dec bool on = true\nprintln(on)  // true"],
            expected_output: &["true"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("string"),
            description: "`string` is a string enclosed in double quotes",
            examples: &["dec string name = \"Mohamed\"\nprintln(name)  // Mohamed"],
            expected_output: &["Mohamed"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("char"),
            description: "`char` is a single character enclosed in single quotes",
            examples: &["dec char letter = 'a'\nprintln(letter)  // 'a'"],
            expected_output: &["'a'"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("escape sequences"),
            description: "both string and character literals support escape sequences introduced with `\\\\`",
            examples: &[
                "// common escapes\ndec string s = \"line1\\nline2\"\nprintln(s)\n\n// control characters\ndec string bell = \"\\a\"\ndec string tab = \"\\t\"\nprintln(bell)\nprintln(tab)\n\n// hex byte (1-2 digits)\ndec char a = '\\x41'\nprintln(a)  // A\n\n// unicode (4 digits)\ndec string u = \"\\u0041\"\nprintln(u)  // A\n\n// unicode (braced, 1-6 digits)\ndec string emoji = \"\\u{1F600}\"\nprintln(emoji)",
            ],
            expected_output: &["line1", "line2", "\x07", "\t", "A", "A", "\u{1F600}"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("byte"),
            description: "`byte` is an unsigned 8-bit integer (0-255); unlike the other primitives, a bare integer literal is always typed `int`, never `byte` - get a byte value with `<literal> as byte` (see the `byte` concept for the full casting rules)",
            examples: &["dec byte b = 10 as byte\nprintln(b)  // 10"],
            expected_output: &["10"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Pitfall,
            title: Some("literals don't default to byte"),
            description: "a bare integer literal is always `int`, even a small one that would fit in a byte - `dec byte b = 10` (without `as byte`) is a compile-time type mismatch, not an implicit narrowing",
            examples: &[
                "// dec byte b = 10  // error: type mismatch: expected byte, got int\ndec byte b = 10 as byte\nprintln(b)  // 10",
            ],
            expected_output: &["10"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Note,
            title: Some("handle"),
            description: "`handle` is an opaque, module-scoped type returned by several stdlib modules (`std::gui`, `std::net`, `std::audio`, `std::c`, `std::http`) instead of an `int`. You can only obtain a handle from the function that creates it and hand it back to that same module's functions - `dec handle x = ...` is valid, but there's no way to construct or compare handles yourself. `handle` also works in function signatures (`fn shut(handle h)` / `-> result[handle]`), matching any concrete kind. Printing one works, though it only shows the kind and id, e.g. `<Gui handle #1>`",
            examples: &["dec handle window = result_unwrap(gui_window(\"My App\", 400, 300))"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("union types"),
            description: "`any[T, ...]` is a union: a value of any one member type. The declared union sticks - `dec any[int, string] a = 1` keeps type `any[int, string]`, so reads must narrow with `match __type_of(a)` or a numeric `as` cast. Operators, indexing, and method calls require every member to resolve, failing loudly otherwise. Members normalize at parse (nested unions flatten, duplicates drop); empty and single-member lists are errors",
            examples: &["dec any[int, string] a = 1\ndec int b = a as int"],
            expected_output: &[],
        },
    ],
    pitfalls: &[
        "a bare integer literal is always `int`, never `byte`, no matter how small - `dec byte b = 10` without `as byte` is a compile-time type mismatch",
        "`handle` in an annotation matches any concrete handle kind in either direction - `fn shut(handle h) { close(h) }` accepts a file handle, and `-> result[handle]` returns flow through `?` like any other result",
        "a union never narrows implicitly - `dec int b = a` where `a` is `any[int, string]` is a mismatch even when `a` currently holds an int; narrow with `as` (numerics) or `match`",
    ],
    related: &["byte", "casting", "variables"],
    related_stdlib: &["types"],
    since: Some("v0.1.5"),
};
