use crate::entry::{ConceptCategory, ConceptEntry, DescriptionEntry, DescriptionKind};

pub static OPERATORS: ConceptEntry = ConceptEntry {
    name: "operators",
    summary: "the arithmetic, comparison, logical-not, unary, method-call, and grouping operators, and the precedence rules that connect them",
    category: ConceptCategory::Syntax,
    prerequisites: &["types"],
    descriptions: &[
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("arithmetic"),
            description: "arithmetic: `+`, `-`, `*`, `/`; both sides must already be the same type (int, float, or byte) - there's no implicit promotion between them",
            examples: &[
                "println(10 + 5)   // 15",
                "println(10 - 3)   // 7",
                "println(4 * 3)    // 12",
                "println(10 / 2)   // 5",
            ],
            expected_output: &["15", "7", "12", "5"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Pitfall,
            title: Some("+ doesn't concatenate strings"),
            description: "`+` only supports int+int, float+float, and byte+byte - there's no string concatenation operator; build strings with the `str` stdlib module instead",
            examples: &["// dec string s = \"a\" + \"b\"  // error: type mismatch on +"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Pitfall,
            title: Some("division truncates and can error"),
            description: "int and byte division truncates toward zero and raises a runtime error on division by zero; float division never errors and follows IEEE-754 instead",
            examples: &["println(7 / 2)  // 3, not 3.5"],
            expected_output: &["3"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("ordering comparisons"),
            description: "`<`, `<=`, `>`, `>=` compare int, float, or byte operands of the same type and always return bool",
            examples: &["println(3 < 10)    // true", "println(10 >= 10)  // true"],
            expected_output: &["true", "true"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("equality comparisons"),
            description: "`==` and `!=` compare any pair of matching types - not just numbers - and always return bool",
            examples: &[
                "println(5 == 5)          // true",
                "println(\"rl\" == \"rl\")  // true",
            ],
            expected_output: &["true", "true"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Note,
            title: Some("logical not"),
            description: "`!` negates a bool; see the `logical operators` concept for `and`/`or` and short-circuiting",
            examples: &["println(!true)  // false"],
            expected_output: &["false"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("unary negation"),
            description: "unary `-` negates a numeric value",
            examples: &["dec int x = 5\nprintln(-x)  // -5"],
            expected_output: &["-5"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("method-style calls"),
            description: "method-style call with `.` - calls a function with the value as first argument",
            examples: &[
                "get std::str::to_upper\n\ndec string s = \"hello\"\nprintln(s.to_upper())  // HELLO",
                "get std::array::arr_push\n\ndec arr[int] nums = [1, 2]\nnums = nums.arr_push(3)\nprintln(nums)  // [1, 2, 3]",
            ],
            expected_output: &["HELLO", "[1, 2, 3]"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("grouping"),
            description: "grouping with `()` controls evaluation order",
            examples: &[
                "dec int x = (2 + 3) * 4\nprintln(x)  // 20",
                "dec int y = 2 + 3 * 4\nprintln(y)  // 14",
            ],
            expected_output: &["20", "14"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("operator precedence, loosest to tightest"),
            description: "from loosest to tightest binding: `and`/`or` -> `==`/`!=` -> `<`/`<=`/`>`/`>=` (sharing this level with the compound-assignment operators `+=`/`-=`/`*=`/`/=`) -> `+`/`-` -> `*`/`/` -> unary `!`/`-` -> postfix `.` method calls, `as` casts, and `?` propagation, which bind tightest and chain left-to-right",
            examples: &[],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Pitfall,
            title: Some("compound assignment shares precedence with comparisons"),
            description: "compound assignment (`+=`, `-=`, `*=`, `/=`) is parsed at the same precedence level as `<`/`<=`/`>`/`>=`, one level looser than `+`/`-` - it isn't its own lowest-of-all precedence level the way plain assignment often is in other languages",
            examples: &[],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Pitfall,
            title: Some("null and operators"),
            description: "every operator except `==`/`!=` raises a runtime error if given a `null` operand; `==`/`!=` special-case `null` instead - `null == null` is `true`, and `null` compared to anything else is `false`",
            examples: &["dec int x = null\nprintln(x == null)  // true"],
            expected_output: &["true"],
        },
    ],
    pitfalls: &[
        "`+` `-` `*` `/` require both sides to already be the same type (int, float, or byte) - there's no implicit promotion, and `+` doesn't concatenate strings",
        "int and byte division truncates toward zero and raises a runtime error on division by zero; float division never errors and follows IEEE-754 instead",
        "compound assignment (`+=` `-=` `*=` `/=`) is parsed at the same precedence level as `<`/`<=`/`>`/`>=`, one level looser than `+`/`-`",
        "every operator except `==`/`!=` raises a runtime error on a `null` operand; `==`/`!=` special-case `null` instead",
    ],
    related: &["casting", "logical operators", "null", "variables"],
    related_stdlib: &["str", "types"],
    since: Some("v0.1.5"),
};
