use crate::entry::{ConceptCategory, ConceptEntry, DescriptionEntry, DescriptionKind};

pub static ENTRY_POINTS: ConceptEntry = ConceptEntry {
    name: "entry points",
    summary: "how a program's entry point is chosen and run - script mode by default, `fn main()`, or an explicit `!#[entry]`/`!#[init]`/`!#[final]`/`!#[test]`-marked function, all executed in a fixed order",
    category: ConceptCategory::Syntax,
    prerequisites: &["functions"],
    descriptions: &[
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("script mode"),
            description: "source files work as scripts when no entry function is present - top-level statements just run top to bottom",
            examples: &["println(\"just runs top to bottom\")"],
            expected_output: &["just runs top to bottom"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("fn main"),
            description: "if a file declares `fn main()`, `rl run` registers declarations and runs `main()` instead of evaluating top-level expressions",
            examples: &["fn main() {\n    std::io::println(\"hello\")\n}"],
            expected_output: &["hello"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("!#[entry]"),
            description: "a different zero-argument function can be selected as the entry point with `!#[entry]` - if both `!#[entry]` and `fn main()` are present, the explicit `!#[entry]` function wins and `main` is treated as an ordinary function",
            examples: &["!#[entry]\nfn start() {\n    std::io::println(\"hello\")\n}"],
            expected_output: &["hello"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Pitfall,
            title: Some("only one !#[entry] is allowed"),
            description: "declaring more than one `!#[entry]` function is a runtime error ('multiple !#[entry] functions found') - the checker doesn't catch this at compile time, only actually running the program does",
            examples: &[],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("!#[init]"),
            description: "`!#[init]` marks a zero-argument function to run once before the entry point",
            examples: &["!#[init]\nfn setup() {\n    std::io::println(\"starting up\")\n}"],
            expected_output: &["starting up"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("!#[final]"),
            description: "`!#[final]` marks a zero-argument function to run once after the entry point finishes",
            examples: &["!#[final]\nfn cleanup() {\n    std::io::println(\"shutting down\")\n}"],
            expected_output: &["shutting down"],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("!#[test]"),
            description: "`!#[test]` marks a zero-argument function as a test, run automatically alongside the rest of the program - there's no separate test-only mode or CLI command",
            examples: &[
                "!#[test]\nfn adds_correctly() {\n    if 2 + 2 != 4 {\n        panic(\"math is broken\")\n    }\n}",
            ],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Pitfall,
            title: Some("tests/inits/finals only run when there's an entry point"),
            description: "`!#[init]`, `!#[final]`, and `!#[test]` only do anything when the file also has an entry point (`!#[entry]` or `fn main()`) - in a script-mode file with neither, they're just ordinary function declarations that are never called automatically",
            examples: &[],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Pitfall,
            title: Some("execution order, and what skips the rest"),
            description: "when an entry point exists, everything runs in a fixed order: every `!#[test]` function, then every `!#[init]` function, then the entry function, then every `!#[final]` function - each stage's functions run in file order, and if any function in an earlier stage errors, every later stage (including `!#[final]`) is skipped entirely, since there's no finally-style guarantee",
            examples: &[],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Pitfall,
            title: Some("the checker doesn't validate these attributes"),
            description: "the type checker ignores function attributes entirely - a `!#[entry]`/`!#[init]`/`!#[final]`/`!#[test]` function with parameters, or a second `!#[entry]`, type-checks without error; since these functions are always invoked with zero arguments, one that takes parameters only fails at runtime ('function expects N argument(s), got 0')",
            examples: &[],
            expected_output: &[],
        },
    ],
    pitfalls: &[
        "declaring more than one `!#[entry]` function is only caught at runtime ('multiple !#[entry] functions found'), not by the checker",
        "`!#[init]`, `!#[final]`, and `!#[test]` only run automatically when the file also has an entry point (`!#[entry]` or `fn main()`) - otherwise they're just ordinary, never-called functions",
        "execution order is tests -> inits -> entry -> finals, and an error in any earlier stage skips every later one, including `!#[final]` - there's no finally-style guarantee",
        "the checker doesn't validate these attributes at all - a parameterized entry/init/final/test function type-checks fine and only fails when it's actually called with zero arguments at runtime",
    ],
    related: &["functions", "result"],
    related_stdlib: &[],
    since: Some("v0.1.5"),
};
