//! Static registry of every RL-visible stdlib function name per namespace.
//!
//! Used to expand `get * from std::ns` imports and to resolve method calls
//! against imported namespaces. Mirrors the tree built by `root()` in
//! `rl-vm/src/stdlib/mod.rs` (short names: `str`, `res`, `term`). Includes
//! names not yet implemented by the transpiler so wildcard imports and
//! method calls on them fail loudly instead of silently miscompiling.

/// True when `name` is exported by stdlib `namespace` (e.g. "std::str").
/// `namespace` is the full path joined with "::" ("std::math::consts").
pub fn namespace_provides(namespace: &str, name: &str) -> bool {
    match namespace {
        "std::cli" => matches!(
            name,
            "parse_args"
                | "parse_args_or_exit"
                | "usage_string"
                | "prompt"
                | "prompt_password"
                | "prompt_confirm"
                | "prompt_choice"
                | "shell_split"
                | "shell_join"
                | "read_line_editable"
                | "read_line_with_history"
                | "progress_bar"
                | "spinner_tick"
        ),
        "std::io" => matches!(
            name,
            "print"
                | "println"
                | "read"
                | "read_int"
                | "read_float"
                | "read_file"
                | "read_lines"
                | "read_bytes"
                | "write_file"
                | "append_file"
                | "delete_file"
                | "read_all_stdin"
                | "decode_utf8"
                | "encode_utf8"
                | "isatty"
                | "eprint"
                | "eprintln"
        ),
        "std::collections" => matches!(
            name,
            "set_add"
                | "set_remove"
                | "set_contains"
                | "set_len"
                | "set_is_empty"
                | "set_to_array"
                | "map_contains"
                | "map_remove"
                | "map_len"
                | "map_is_empty"
                | "map_to_array"
                | "map_get"
                | "map_keys"
                | "map_values"
                | "map_clear"
                | "map_merge"
                | "set_union"
                | "set_intersection"
                | "set_difference"
                | "set_symmetric_difference"
                | "set_is_subset"
                | "set_is_superset"
                | "map_get_or"
                | "map_get_or_insert"
                | "heap_push"
                | "heap_pop"
                | "heap_peek"
                | "deque_push_front"
                | "deque_pop_front"
                | "bisect_left"
                | "bisect_right"
                | "sorted_insert"
        ),
        "std::array" => matches!(
            name,
            "arr_push"
                | "arr_pop"
                | "arr_insert"
                | "arr_remove"
                | "arr_reverse"
                | "arr_concat"
                | "arr_first"
                | "arr_last"
                | "arr_unique"
                | "arr_flatten"
                | "arr_slice"
                | "arr_contains"
                | "arr_index_of"
                | "arr_count"
                | "arr_is_empty"
                | "arr_fill"
                | "arr_range"
                | "arr_sum"
                | "arr_product"
                | "arr_max"
                | "arr_min"
                | "arr_sort"
                | "arr_zip"
                | "arr_map"
                | "arr_filter"
                | "arr_find"
                | "arr_find_index"
                | "arr_all"
                | "arr_any"
                | "arr_flat_map"
                | "arr_for_each"
                | "arr_reduce"
                | "arr_sort_by"
                | "arr_chunk"
                | "arr_windows"
                | "arr_swap"
                | "arr_partition"
                | "arr_max_by"
                | "arr_min_by"
                | "arr_zip_longest"
                | "arr_cycle_take"
                | "len"
        ),
        "std" => matches!(name, "len"),
        "std::c" => matches!(
            name,
            "compile" | "load" | "has_symbol" | "close" | "clear_cache" | "call"
        ),
        "std::audio" => matches!(
            name,
            "play_file"
                | "play_file_async"
                | "beep"
                | "sound_pause"
                | "sound_resume"
                | "sound_stop"
                | "sound_is_paused"
                | "sound_set_volume"
                | "sound_get_volume"
                | "sound_set_speed"
                | "sound_seek"
                | "sound_is_finished"
                | "sound_wait"
                | "list_output_devices"
                | "set_output_device"
                | "set_master_volume"
                | "audio_duration"
                | "audio_file_info"
        ),
        "std::gui" => matches!(
            name,
            "gui_window"
                | "gui_button"
                | "gui_label"
                | "gui_checkbox"
                | "gui_textbox"
                | "gui_textarea"
                | "gui_dropdown"
                | "gui_radio_group"
                | "gui_slider"
                | "gui_number_input"
                | "gui_progress_bar"
                | "gui_separator"
                | "gui_image"
                | "gui_set_text"
                | "gui_get_text"
                | "gui_set_visible"
                | "gui_is_visible"
                | "gui_on_click"
                | "gui_on_change"
                | "gui_on_submit"
                | "gui_on_key"
                | "gui_on_close"
                | "gui_is_checked"
                | "gui_set_checked"
                | "gui_get_selected_index"
                | "gui_set_selected_index"
                | "gui_get_selected"
                | "gui_get_value"
                | "gui_set_value"
                | "gui_set_progress"
                | "gui_get_progress"
                | "gui_set_pos"
                | "gui_get_pos"
                | "gui_set_z"
                | "gui_get_z"
                | "gui_remove"
                | "gui_window_set_title"
                | "gui_window_set_background"
                | "gui_window_set_size"
                | "gui_window_set_pos"
                | "gui_window_set_decorated"
                | "gui_window_set_icon"
                | "gui_run"
                | "gui_close"
                | "gui_quit"
                | "gui_set_font_size"
                | "gui_set_color"
                | "gui_set_bg_color"
                | "gui_set_tooltip"
                | "gui_get_window_size"
                | "gui_get_window_pos"
        ),
        "std::fs" => matches!(
            name,
            "mkdir"
                | "mkdir_all"
                | "rmdir"
                | "rmdir_all"
                | "list_dir"
                | "list_dir_names"
                | "copy_file"
                | "move_file"
                | "file_size"
                | "file_modified"
                | "file_created"
                | "file_accessed"
                | "file_permissions"
                | "set_permissions"
                | "temp_dir"
                | "temp_file"
                | "temp_file_in"
                | "rename_file"
                | "touch"
                | "truncate_file"
                | "glob"
                | "walk_dir"
                | "symlink"
                | "readlink"
                | "hardlink"
                | "realpath"
                | "lock_file"
                | "unlock_file"
                | "read_file"
                | "read_lines"
                | "read_bytes"
                | "write_file"
                | "append_file"
                | "delete_file"
                | "path_exists"
                | "path_is_dir"
                | "path_is_file"
                | "path_canonicalize"
                | "path_absolute"
                | "path_expand_home"
                | "path_relative"
                | "open"
                | "close"
                | "read_handle"
                | "write_handle"
                | "seek"
                | "flush"
                | "read_all"
                | "readline"
                | "copy_dir"
                | "dir_size"
                | "is_symlink"
        ),
        "std::http" => matches!(
            name,
            "http_server_start"
                | "http_server_recv"
                | "http_server_try_recv"
                | "http_server_stop"
                | "http_request_method"
                | "http_request_url"
                | "http_request_header"
                | "http_request_body"
                | "http_respond"
                | "http_get"
                | "http_post"
                | "http_request"
        ),
        "std::net" => matches!(
            name,
            "tcp_listen"
                | "tcp_accept"
                | "tcp_connect"
                | "tcp_read"
                | "tcp_write"
                | "tcp_peer_addr"
                | "tcp_local_addr"
                | "tcp_set_timeout"
                | "tcp_set_nonblocking"
                | "tcp_shutdown"
                | "tcp_close"
                | "udp_bind"
                | "udp_connect"
                | "udp_send"
                | "udp_send_to"
                | "udp_recv"
                | "udp_recv_from"
                | "udp_close"
                | "resolve"
        ),
        "std::process" => matches!(
            name,
            "args"
                | "exit"
                | "pid"
                | "sleep"
                | "env"
                | "set_env"
                | "remove_env"
                | "env_keys"
                | "cwd"
                | "set_cwd"
                | "os_name"
                | "arch"
                | "num_cpus"
                | "parent_pid"
                | "process_exists"
                | "process_running"
                | "exec"
                | "with_exec"
                | "exec_fg"
                | "with_exec_fg"
                | "exec_code"
                | "with_exec_code"
                | "exec_lines"
                | "with_exec_lines"
                | "exec_with_stdin"
                | "with_exec_with_stdin"
                | "exec_with_env"
                | "with_exec_with_env"
                | "exec_with_cwd"
                | "with_exec_with_cwd"
                | "exec_with_timeout"
                | "exec_background"
                | "with_exec_background"
                | "wait_pid"
                | "term_pid"
                | "kill_pid"
                | "pipe"
                | "pipe_all"
        ),
        "std::term" => matches!(
            name,
            "term_enter"
                | "term_leave"
                | "term_clear"
                | "term_clear_line"
                | "term_move"
                | "term_move_to_col"
                | "term_move_to_row"
                | "term_move_up"
                | "term_move_down"
                | "term_move_left"
                | "term_move_right"
                | "term_next_line"
                | "term_prev_line"
                | "term_save_cursor"
                | "term_restore_cursor"
                | "term_hide_cursor"
                | "term_show_cursor"
                | "term_get_size"
                | "term_get_cursor_pos"
                | "term_set_size"
                | "term_set_title"
                | "term_scroll_up"
                | "term_scroll_down"
                | "term_print"
                | "term_flush"
                | "term_set_fg"
                | "term_set_bg"
                | "term_reset_color"
                | "term_fg"
                | "term_bg"
                | "term_bold"
                | "term_dim"
                | "term_italic"
                | "term_underline"
                | "term_blink"
                | "term_reverse"
                | "term_crossed_out"
                | "term_reset_attr"
                | "term_enable_wrap"
                | "term_disable_wrap"
                | "term_begin_sync"
                | "term_end_sync"
                | "term_enable_mouse"
                | "term_disable_mouse"
                | "term_read_key"
                | "term_poll"
        ),
        "std::bitwise" => matches!(
            name,
            "bit_and"
                | "bit_or"
                | "bit_xor"
                | "bit_not"
                | "bit_shift_left"
                | "bit_shift_right"
                | "count_bits"
                | "leading_zeros"
                | "trailing_zeros"
                | "rotate_left"
                | "rotate_right"
                | "bit_set"
                | "bit_clear"
                | "bit_toggle"
                | "bit_is_set"
        ),
        "std::debug" => matches!(
            name,
            "assert"
                | "assert_eq"
                | "assert_ne"
                | "assert_lt"
                | "assert_le"
                | "assert_gt"
                | "assert_ge"
                | "assert_approx_eq"
                | "panic"
                | "unreachable"
                | "todo"
                | "type_of"
                | "dbg"
                | "warn"
                | "stack_trace"
                | "bench"
        ),
        "std::math" => matches!(
            name,
            "abs"
                | "ceil"
                | "floor"
                | "round"
                | "clamp"
                | "max"
                | "min"
                | "mod"
                | "pow"
                | "log"
                | "sqrt"
                | "log2"
                | "log10"
                | "sin"
                | "cos"
                | "tan"
                | "atan"
                | "acos"
                | "asin"
                | "degrees"
                | "radians"
                | "exp"
                | "sign"
                | "atan2"
                | "hypot"
                | "lerp"
                | "map_range"
                | "factorial"
                | "fibonacci"
                | "gcd"
                | "lcm"
                | "is_prime"
        ),
        "std::math::consts" => matches!(
            name,
            "E" | "PI"
                | "PHI"
                | "TAU"
                | "INF"
                | "NAN"
                | "is_inf"
                | "is_nan"
                | "FRAC_1_PI"
                | "FRAC_2_PI"
                | "FRAC_1_SQRT_2"
                | "FRAC_2_SQRT_PI"
                | "EULER_GAMMA"
                | "LN_10"
                | "LN_2"
                | "LOG2_E"
                | "LOG2_10"
                | "LOG10_2"
                | "LOG10_E"
                | "FRAC_PI_2"
                | "FRAC_PI_3"
                | "FRAC_PI_4"
                | "FRAC_PI_6"
                | "FRAC_PI_8"
                | "SQRT_2"
        ),
        "std::path" => matches!(
            name,
            "path_exists"
                | "path_is_dir"
                | "path_is_file"
                | "path_is_absolute"
                | "path_is_relative"
                | "path_starts_with"
                | "path_ends_with"
                | "path_extension"
                | "path_filename"
                | "path_parent"
                | "path_stem"
                | "path_pop"
                | "path_normalize"
                | "path_absolute"
                | "path_canonicalize"
                | "path_expand_home"
                | "path_split"
                | "path_split_extension"
                | "path_components"
                | "path_join"
                | "path_push"
                | "path_set_extension"
                | "path_with_file_name"
                | "path_relative"
                | "path_join_many"
        ),
        "std::random" => matches!(
            name,
            "rand_int"
                | "rand_float"
                | "rand_bool"
                | "rand_bool_weighted"
                | "rand_char"
                | "rand_byte"
                | "rand_int_range"
                | "rand_float_range"
                | "rand_dice"
                | "rand_range"
                | "rand_range_step"
                | "rand_string"
                | "rand_dices"
                | "rand_bytes"
                | "rand_choice"
                | "rand_choices"
                | "rand_sample"
                | "rand_shuffle"
                | "rand_seed"
        ),
        "std::res" => matches!(
            name,
            "is_ok"
                | "is_err"
                | "result_unwrap"
                | "result_unwrap_err"
                | "result_unwrap_or"
                | "result_map"
                | "result_map_err"
                | "result_and_then"
                | "result_unwrap_or_else"
        ),
        "std::str" => matches!(
            name,
            "to_upper"
                | "to_lower"
                | "trim"
                | "trim_end"
                | "trim_start"
                | "reverse"
                | "repeat"
                | "is_empty"
                | "contains"
                | "starts_with"
                | "ends_with"
                | "replace"
                | "pad_left"
                | "pad_right"
                | "count"
                | "index_of"
                | "bytes"
                | "chars"
                | "split"
                | "char_at"
                | "slice"
                | "join"
                | "concat"
                | "format"
                | "strip_prefix"
                | "strip_suffix"
                | "last_index_of"
                | "split_once"
                | "lines"
                | "wrap"
                | "indent"
                | "dedent"
                | "diff_lines"
                | "is_alpha"
                | "is_numeric"
                | "is_whitespace"
                | "unicode_category"
        ),
        "std::time" => matches!(
            name,
            "time_now"
                | "time_now_ms"
                | "time_add"
                | "time_diff"
                | "format_time"
                | "format_date_str"
                | "format_time_str"
                | "time_parts"
                | "monotonic_now"
        ),
        "std::types" => matches!(
            name,
            "is_bool"
                | "is_null"
                | "is_char"
                | "is_int"
                | "is_float"
                | "is_string"
                | "is_byte"
                | "is_error"
                | "error_unwrap"
                | "to_bin"
                | "to_hex"
                | "to_oct"
                | "to_bool"
                | "to_byte"
                | "to_char"
                | "to_float"
                | "to_int"
                | "to_string"
                | "is_array"
                | "is_map"
                | "is_set"
                | "is_tuple"
                | "is_function"
                | "is_uint"
                | "is_sbyte"
                | "is_bsbyte"
                | "is_bbyte"
                | "is_sint"
                | "is_suint"
                | "is_sfloat"
                | "is_c_handle"
                | "is_net_handle"
                | "is_http_handle"
                | "is_audio_handle"
                | "is_gui_handle"
                | "is_file_handle"
        ),
        "std::rl" => matches!(
            name,
            "lex" | "eval" | "eval_isolated" | "check" | "rl_version" | "source_name"
        ),
        _ => false,
    }
}
