use crate::entry::{ConceptCategory, ConceptEntry, DescriptionEntry, DescriptionKind};

pub static TOOLING: ConceptEntry = ConceptEntry {
    name: "tooling",
    summary: "the `rl` command-line tool: running, checking, compiling, packaging, and formatting `.rl` files, an interactive REPL, project scaffolding, documentation, and CI workflow generation",
    category: ConceptCategory::Syntax,
    prerequisites: &[],
    descriptions: &[
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl run"),
            description: "`rl run <file>` lexes, parses, and evaluates a `.rl` source file; running a `.rlc` file instead automatically uses the bytecode VM",
            examples: &["rl run main.rl", "rl run script.rl -- --verbose input.txt"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Pitfall,
            title: Some("flags must come before the file"),
            description: "any arguments after the file path (or after a literal `--`) are forwarded to the script as its own `argv` - flags meant for `rl run` itself, like `--vm` or `--cranelift`, must come before the file path",
            examples: &["rl run script.rl -- --verbose input.txt"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl check"),
            description: "`rl check <file>` type-checks a file and reports errors without running it",
            examples: &["rl check main.rl"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl repl"),
            description: "`rl repl` starts an interactive TUI read-eval-print loop with syntax highlighting and history",
            examples: &["rl repl"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl dev"),
            description: "`rl dev` reads `rl.toml` in the current directory and runs the project's configured entry file",
            examples: &["rl dev"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl new"),
            description: "`rl new <name>` scaffolds a new project directory with an `rl.toml` and a `main.rl`; pass `--no-git` to skip running `git init`",
            examples: &["rl new my-project", "rl new my-project --no-git"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("rl docs"),
            description: "`rl docs [topic]` prints the language reference, stdlib docs, and tutorials; with no topic it prints everything, and a topic name searches across all categories for a match (narrow with `--stdlib`, `--concept`, or `--tutorial`) - add `--tui` to browse interactively instead, or `--json` for machine-readable output",
            examples: &["rl docs", "rl docs print", "rl docs loops --concept --json"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("rl docs --generate"),
            description: "`rl docs --generate` builds a documentation website for the current project from its `///` doc comments (see the `comments` concept); add `--html` for an HTML build alongside it, and `--out-dir` to change where the site is written",
            examples: &["rl docs --generate", "rl docs --generate --html"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("rl workflows"),
            description: "`rl workflows` scaffolds GitHub Actions workflow YAML for the project - `--check` generates a workflow that runs `rl check` on push/PR, `--package` generates one that packages and releases a binary; at least one of the two flags is required",
            examples: &["rl workflows --check", "rl workflows --package"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("rl package"),
            description: "`rl package <file>` bundles a `.rl` source file into a self-contained binary; `--output` names the resulting binary, and `--vm` compiles to `.rlc` bytecode first and embeds that instead of the raw source, so the packaged binary skips lexing and parsing at startup",
            examples: &[
                "rl package script.rl",
                "rl package script.rl --output myprogram --vm",
            ],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("rl compile"),
            description: "`rl compile <file>` lexes, parses, resolves, and compiles a `.rl` file to `.rlc` bytecode; the resulting file can be run directly with `rl run`, skipping the lex/parse/compile step",
            examples: &[
                "rl compile script.rl",
                "rl compile script.rl --output out.rlc",
            ],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl format"),
            description: "`rl format <file>` reformats a `.rl` source file and writes the result back in place",
            examples: &["rl format main.rl"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Note,
            title: Some("rl lsp"),
            description: "`rl lsp` starts the Language Server Protocol server over stdio for editor integration; it's meant to be launched by an editor rather than run by hand, and is only present in builds compiled with the `lsp` feature",
            examples: &["rl lsp"],
            expected_output: &[],
        },
    ],
    pitfalls: &[
        "extra arguments after the file path in `rl run` are forwarded to the script as its `argv` - flags meant for `rl run` itself must come before the file path",
        "running a `.rlc` file with `rl run` automatically switches to the bytecode VM based on the file extension, even without passing `--vm`",
        "`rl workflows` requires at least one of `--check` or `--package` - running it with neither is an error",
        "`rl lsp` only exists in builds compiled with the `lsp` feature - it may not be present in every build of the CLI",
    ],
    related: &["comments"],
    related_stdlib: &[],
    since: Some("v0.1.5"),
};
