use crate::entry::{ConceptCategory, ConceptEntry, DescriptionEntry, DescriptionKind};

pub static TOOLING: ConceptEntry = ConceptEntry {
    name: "tooling",
    summary: "the rl-lang binaries: `rl` (core), `rlc` (compiler/runner), `rlt` (transpiler), `rlrepl` (TUI REPL), `rlsp` (LSP), `rldocs` (docs), and `rlm` (toolchain manager)",
    category: ConceptCategory::Tooling,
    prerequisites: &[],
    descriptions: &[
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("binary overview"),
            description: "rl-lang ships as separate binaries, each focused on a specific task. `rl` is the core CLI for running, checking, and project management. `rlc` is a lean compiler and runner. `rlt` transpiles to C99. `rlrepl`, `rlsp`, and `rldocs` are standalone tools. `rlm` manages the toolchain.",
            examples: &[],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl (core)"),
            description: "`rl` is the main CLI with subcommands: `run`, `check`, `new`, `dev`, `format`, `print`, `package`, `workflows`, and `pm`. it includes the VM runtime, REPL, docs, and package manager.",
            examples: &["rl run script.rl", "rl check main.rl", "rl new my-project", "rl dev"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rlc (compiler + runner)"),
            description: "`rlc` is a lean compiler and runner. `rlc compile <file>` produces `.rlc` bytecode. `rlc run <file>` compiles and runs in one step. `rlc run <file.rlc>` runs pre-compiled bytecode. unlike `rl`, it has no project management, REPL, or docs commands.",
            examples: &[
                "rlc compile script.rl",
                "rlc run script.rl",
                "rlc run script.rlc",
            ],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rlt (transpiler)"),
            description: "`rlt` transpiles `.rl` source to C99. the output can be compiled with gcc, clang, or any C compiler. use `--compile` to invoke cc automatically, and `--runtime` to emit the C runtime files.",
            examples: &[
                "rlt script.rl",
                "rlt script.rl --compile",
                "rlt script.rl --runtime --compile --opt O3",
            ],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rlrepl (interactive REPL)"),
            description: "`rlrepl` starts an interactive TUI read-eval-print loop with syntax highlighting and history.",
            examples: &["rlrepl"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rlsp (LSP server)"),
            description: "`rlsp` starts the Language Server Protocol server over stdio for editor integration. it's meant to be launched by an editor rather than run by hand.",
            examples: &["rlsp"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rldocs (documentation viewer)"),
            description: "`rldocs` prints the language reference, stdlib docs, and tutorials. add `--tui` for interactive browsing, or `--json` for machine-readable output.",
            examples: &["rldocs", "rldocs print", "rldocs --tui"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl new"),
            description: "`rl new <name>` scaffolds a new project directory with an `rl.toml` and a `main.rl`. pass `--no-git` to skip `git init`. pass `--script` for a standalone `.rl` script. pass `--lib` for a library project with `src/lib.rl`.",
            examples: &[
                "rl new my-project",
                "rl new my-project --no-git",
                "rl new --script hello",
                "rl new my-lib --lib",
            ],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Explanation,
            title: Some("shebang scripts"),
            description: "rl supports shebang (`#!`) headers in `.rl` files. the lexer strips the first line if it starts with `#!`. use `rl new --script <name>` to create a standalone script, or write your own `#!/path/to/rl run` header. make the file executable with `chmod +x` and run it directly.",
            examples: &["rl new --script hello", "chmod +x hello.rl", "./hello.rl"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl docs"),
            description: "`rl docs [topic]` prints the language reference, stdlib docs, and tutorials. with no topic it prints everything. a topic name searches across all categories. add `--tui` to browse interactively, or `--json` for machine output.",
            examples: &["rl docs", "rl docs print", "rl docs loops --concept --json"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl workflows"),
            description: "`rl workflows` scaffolds GitHub Actions workflow YAML. `--check` generates a workflow that runs `rl check` on push/PR. `--package` generates one that packages and releases a binary. at least one flag is required.",
            examples: &["rl workflows --check", "rl workflows --package"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl package"),
            description: "`rl package <file>` bundles a `.rl` source file into a self-contained binary. `--output` names the binary. `--vm` compiles to `.rlc` bytecode first and embeds that instead of raw source.",
            examples: &[
                "rl package script.rl",
                "rl package script.rl --output myprogram --vm",
            ],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl format"),
            description: "`rl format <file>` reformats a `.rl` source file in place.",
            examples: &["rl format main.rl"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rl pm"),
            description: "`rl pm` manages project dependencies. see the `package manager` concept for full documentation.",
            examples: &["rl pm install", "rl pm list"],
            expected_output: &[],
        },
        DescriptionEntry {
            kind: DescriptionKind::Syntax,
            title: Some("rlm (toolchain manager)"),
            description: "`rlm` installs, updates, and manages rl-lang binaries. see the `rlm (toolchain manager)` concept for full documentation.",
            examples: &["rlm install", "rlm update", "rlm list"],
            expected_output: &[],
        },
    ],
    pitfalls: &[
        "`rlc` is a lean alternative to `rl` for compile+run workflows - it has no project management, REPL, or docs",
        "extra arguments after the file path in `rl run` or `rlc run` are forwarded to the script as its `argv` - flags must come before the file path",
        "running a `.rlc` file with `rl run` or `rlc run` automatically uses the bytecode VM based on file extension",
        "`rl workflows` requires at least one of `--check` or `--package` - running it with neither is an error",
    ],
    related: &["comments", "package manager", "rlm (toolchain manager)"],
    related_stdlib: &[],
    since: Some("v0.1.5"),
};
