//! Static name lists for every `std::*` stdlib module.

pub mod cli {
    pub const KEYWORDS: &[&str] = &[
        "parse_args",
        "parse_args_or_exit",
        "usage_string",
        "prompt",
        "prompt_password",
        "prompt_confirm",
        "prompt_choice",
        "shell_split",
        "shell_join",
        "read_line_editable",
        "read_line_with_history",
        "progress_bar",
        "spinner_tick",
    ];
}

pub mod audio {
    pub const KEYWORDS: &[&str] = &[
        "play_file",
        "play_file_async",
        "beep",
        "sound_pause",
        "sound_resume",
        "sound_stop",
        "sound_is_paused",
        "sound_set_volume",
        "sound_get_volume",
        "sound_set_speed",
        "sound_seek",
        "sound_is_finished",
        "sound_wait",
        "list_output_devices",
        "set_output_device",
        "set_master_volume",
        "audio_duration",
        "audio_file_info",
    ];
}

pub mod array {
    pub const KEYWORDS: &[&str] = &[
        "arr_push",
        "arr_pop",
        "arr_insert",
        "arr_remove",
        "arr_reverse",
        "arr_concat",
        "arr_first",
        "arr_last",
        "arr_max",
        "arr_min",
        "arr_sum",
        "arr_product",
        "arr_unique",
        "arr_is_empty",
        "arr_count",
        "arr_contains",
        "arr_index_of",
        "arr_sort",
        "arr_slice",
        "arr_flatten",
        "arr_range",
        "arr_fill",
        "arr_map",
        "len",
        "arr_filter",
        "arr_all",
        "arr_any",
        "arr_find",
        "arr_find_index",
        "arr_reduce",
        "arr_sort_by",
        "arr_flat_map",
        "arr_for_each",
        "arr_zip",
        "arr_chunk",
        "arr_windows",
        "arr_swap",
        "arr_partition",
        "arr_max_by",
        "arr_min_by",
        "arr_zip_longest",
        "arr_cycle_take",
    ];
}

pub mod bitwise {
    pub const KEYWORDS: &[&str] = &[
        "bit_and",
        "bit_or",
        "bit_xor",
        "bit_not",
        "bit_shift_left",
        "bit_shift_right",
        "count_bits",
        "leading_zeros",
        "trailing_zeros",
        "rotate_left",
        "rotate_right",
        "bit_set",
        "bit_clear",
        "bit_toggle",
        "bit_is_set",
    ];
}

pub mod debug {
    pub const KEYWORDS: &[&str] = &[
        "assert",
        "assert_eq",
        "assert_ne",
        "assert_lt",
        "assert_le",
        "assert_gt",
        "assert_ge",
        "assert_approx_eq",
        "panic",
        "unreachable",
        "todo",
        "dbg",
        "type_of",
        "bench",
        "warn",
        "stack_trace",
    ];
}

pub mod fs {
    pub const KEYWORDS: &[&str] = &[
        "mkdir",
        "mkdir_all",
        "rmdir",
        "rmdir_all",
        "list_dir",
        "list_dir_names",
        "copy_file",
        "move_file",
        "file_size",
        "file_modified",
        "file_created",
        "file_accessed",
        "file_permissions",
        "set_permissions",
        "temp_dir",
        "temp_file",
        "temp_file_in",
        "rename_file",
        "touch",
        "truncate_file",
        "glob",
        "walk_dir",
        "symlink",
        "readlink",
        "hardlink",
        "realpath",
        "lock_file",
        "unlock_file",
        "read_file",
        "read_lines",
        "read_bytes",
        "write_file",
        "append_file",
        "delete_file",
        "path_exists",
        "path_is_dir",
        "path_is_file",
        "path_canonicalize",
        "path_absolute",
        "path_expand_home",
        "copy_dir",
        "dir_size",
        "is_symlink",
    ];
}

pub mod http {
    pub const KEYWORDS: &[&str] = &[
        "http_server_start",
        "http_server_recv",
        "http_server_try_recv",
        "http_request_method",
        "http_request_url",
        "http_request_header",
        "http_request_body",
        "http_respond",
        "http_server_stop",
        "http_get",
        "http_post",
        "http_request",
    ];
}

pub mod io {
    pub const KEYWORDS: &[&str] = &[
        "read",
        "read_int",
        "read_float",
        "read_file",
        "read_lines",
        "delete_file",
        "write_file",
        "append_file",
        "print",
        "println",
        "eprint",
        "read_bytes",
    ];
}

pub mod net {
    pub const KEYWORDS: &[&str] = &[
        "tcp_listen",
        "tcp_accept",
        "tcp_connect",
        "tcp_read",
        "tcp_write",
        "tcp_peer_addr",
        "tcp_local_addr",
        "tcp_set_timeout",
        "tcp_set_nonblocking",
        "tcp_shutdown",
        "tcp_close",
        "udp_bind",
        "udp_connect",
        "udp_send",
        "udp_send_to",
        "udp_recv",
        "udp_recv_from",
        "udp_close",
        "resolve",
    ];
}

pub mod c {
    pub const KEYWORDS: &[&str] = &[
        "compile",
        "load",
        "call",
        "has_symbol",
        "close",
        "clear_cache",
    ];
}

pub mod path {
    pub const KEYWORDS: &[&str] = &[
        "path_exists",
        "path_extension",
        "path_filename",
        "path_is_dir",
        "path_is_file",
        "path_join",
        "path_parent",
        "path_pop",
        "path_push",
        "path_set_extension",
        "path_stem",
    ];
}

pub mod process {
    pub const KEYWORDS: &[&str] = &[
        "args",
        "exit",
        "env",
        "cwd",
        "set_cwd",
        "pid",
        "sleep",
        "exec",
        "with_exec",
        "exec_code",
        "with_exec_code",
        "exec_lines",
        "with_exec_lines",
    ];
}

pub mod random {
    pub const KEYWORDS: &[&str] = &[
        "rand_int",
        "rand_int_range",
        "rand_float",
        "rand_float_range",
        "rand_bool",
        "rand_bool_weighted",
        "rand_dice",
        "rand_dices",
        "rand_range",
        "rand_range_step",
        "rand_choice",
        "rand_choices",
        "rand_sample",
        "rand_shuffle",
        "rand_byte",
        "rand_bytes",
        "rand_char",
        "rand_string",
        "rand_seed",
    ];
}

pub mod result {
    pub const KEYWORDS: &[&str] = &[
        "is_ok",
        "is_err",
        "result_unwrap",
        "result_unwrap_err",
        "result_unwrap_or",
        "result_map",
        "result_map_err",
        "result_and_then",
        "result_unwrap_or_else",
    ];
}

pub mod rl {
    pub const KEYWORDS: &[&str] = &[
        "lex",
        "eval",
        "check",
        "eval_isolated",
        "rl_version",
        "source_name",
    ];
}

pub mod string {
    pub const KEYWORDS: &[&str] = &[
        "to_lower",
        "to_upper",
        "trim",
        "trim_end",
        "trim_start",
        "repeat",
        "is_empty",
        "concat",
        "char_at",
        "bytes",
        "chars",
        "slice",
        "contains",
        "starts_with",
        "ends_with",
        "replace",
        "pad_left",
        "pad_right",
        "split",
        "join",
        "count",
        "index_of",
        "format",
        "strip_prefix",
        "strip_suffix",
        "last_index_of",
        "split_once",
        "lines",
        "wrap",
        "indent",
        "dedent",
        "diff_lines",
        "is_alpha",
        "is_numeric",
        "is_whitespace",
        "unicode_category",
    ];
}

pub mod terminal {
    pub const KEYWORDS: &[&str] = &[
        "term_enter",
        "term_leave",
        "term_clear",
        "term_clear_line",
        "term_move",
        "term_move_up",
        "term_move_down",
        "term_move_left",
        "term_move_right",
        "term_move_to_col",
        "term_move_to_row",
        "term_next_line",
        "term_prev_line",
        "term_save_cursor",
        "term_restore_cursor",
        "term_hide_cursor",
        "term_show_cursor",
        "term_get_size",
        "term_set_size",
        "term_set_title",
        "term_scroll_up",
        "term_scroll_down",
        "term_print",
        "term_flush",
        "term_set_fg",
        "term_set_bg",
        "term_reset_color",
        "term_fg",
        "term_bg",
        "term_bold",
        "term_dim",
        "term_italic",
        "term_underline",
        "term_blink",
        "term_reverse",
        "term_crossed_out",
        "term_reset_attr",
        "term_enable_wrap",
        "term_disable_wrap",
        "term_begin_sync",
        "term_end_sync",
        "term_enable_mouse",
        "term_disable_mouse",
        "term_read_key",
        "term_poll",
        "term_get_cursor_pos",
    ];
}

pub mod time {
    pub const KEYWORDS: &[&str] = &[
        "time_now",
        "time_now_ms",
        "format_time",
        "format_date_str",
        "format_time_str",
        "time_add",
        "time_diff",
        "time_parts",
        "monotonic_now",
    ];
}

pub mod types {
    pub const KEYWORDS: &[&str] = &[
        "to_bin",
        "to_bool",
        "to_char",
        "to_float",
        "to_hex",
        "to_int",
        "to_oct",
        "to_string",
        "is_bool",
        "is_null",
        "is_char",
        "is_int",
        "is_string",
        "is_float",
        "is_error",
        "error_unwrap",
        "to_byte",
        "is_byte",
        "is_uint",
        "is_sbyte",
        "is_bsbyte",
        "is_bbyte",
        "is_sint",
        "is_suint",
        "is_sfloat",
        "is_array",
        "is_map",
        "is_set",
        "is_tuple",
        "is_function",
        "is_c_handle",
        "is_net_handle",
        "is_http_handle",
        "is_audio_handle",
        "is_gui_handle",
        "is_file_handle",
    ];
}

pub mod math {
    pub const KEYWORDS: &[&str] = &[
        "sin",
        "cos",
        "tan",
        "pow",
        "mod",
        "abs",
        "ceil",
        "clamp",
        "floor",
        "round",
        "log",
        "log2",
        "log10",
        "max",
        "min",
        "sqrt",
        "atan",
        "acos",
        "asin",
        "atan2",
        "radians",
        "degrees",
        "exp",
        "factorial",
        "fibonacci",
        "gcd",
        "lcm",
        "hypot",
        "lerp",
        "map_range",
        "sign",
        "is_prime",
    ];

    pub mod constants {
        pub const KEYWORDS: &[&str] = &[
            "E",
            "PI",
            "FRAC_1_PI",
            "FRAC_1_SQRT_2",
            "FRAC_2_PI",
            "FRAC_2_SQRT_PI",
            "FRAC_PI_2",
            "FRAC_PI_3",
            "FRAC_PI_4",
            "FRAC_PI_6",
            "FRAC_PI_8",
            "INF",
            "NAN",
            "is_inf",
            "is_nan",
            "LN_10",
            "LN_2",
            "LOG10_2",
            "LOG10_E",
            "LOG2_10",
            "LOG2_E",
            "SQRT_2",
            "EULER_GAMMA",
            "PHI",
            "TAU",
        ];
    }
}

pub mod collections {
    pub const KEYWORDS: &[&str] = &[
        "set_add",
        "set_contains",
        "set_is_empty",
        "set_len",
        "set_remove",
        "set_to_array",
        "set_union",
        "set_intersection",
        "set_difference",
        "set_symmetric_difference",
        "set_is_subset",
        "set_is_superset",
        "map_contains",
        "map_remove",
        "map_len",
        "map_is_empty",
        "map_to_array",
        "map_get",
        "map_keys",
        "map_values",
        "map_clear",
        "map_merge",
        "map_get_or",
        "map_get_or_insert",
        "heap_push",
        "heap_pop",
        "heap_peek",
        "deque_push_front",
        "deque_pop_front",
        "bisect_left",
        "bisect_right",
        "sorted_insert",
    ];
}

pub mod gui {
    pub const KEYWORDS: &[&str] = &[
        "gui_window",
        "gui_button",
        "gui_label",
        "gui_checkbox",
        "gui_textbox",
        "gui_textarea",
        "gui_dropdown",
        "gui_radio_group",
        "gui_slider",
        "gui_number_input",
        "gui_progress_bar",
        "gui_separator",
        "gui_image",
        "gui_set_text",
        "gui_get_text",
        "gui_set_visible",
        "gui_is_visible",
        "gui_on_click",
        "gui_on_change",
        "gui_on_submit",
        "gui_on_key",
        "gui_on_close",
        "gui_is_checked",
        "gui_set_checked",
        "gui_get_selected_index",
        "gui_set_selected_index",
        "gui_get_selected",
        "gui_get_value",
        "gui_set_value",
        "gui_set_progress",
        "gui_get_progress",
        "gui_set_pos",
        "gui_get_pos",
        "gui_set_z",
        "gui_get_z",
        "gui_remove",
        "gui_window_set_title",
        "gui_window_set_background",
        "gui_window_set_size",
        "gui_window_set_pos",
        "gui_window_set_decorated",
        "gui_window_set_icon",
        "gui_run",
        "gui_close",
        "gui_quit",
        "gui_set_font_size",
        "gui_set_color",
        "gui_set_bg_color",
        "gui_set_tooltip",
        "gui_get_window_size",
        "gui_get_window_pos",
    ];
}
